version: '3.4'

services:
  rewriting.postgres:
    ports:
      - "5432:5432"
    networks:
      - shared_rewriting
    volumes:
      - ~/.docker-conf/mssql/data/:/var/lib/mssql/data
    env_file:
      - env.postgres

  rewriting.rabbitmq:
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672" 
    networks:
      - shared_rewriting
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
  
  rewriting.api:
    ports:
      - "10000:80"
    networks:
      - shared_rewriting
    env_file:
      - env.api

  rewriting.identity:
    ports:
      - "10001:80"
    networks:
      - shared_rewriting
    env_file:
      - env.identity

  rewriting.worker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    env_file:
      - env.worker

networks:
  shared_rewriting:
    name: rewriting
    driver: bridge
