version: '3.4'

services:
  rewriting.postgres:
    ports:
      - "5432:5432"
    networks:
      - shared_rewriting
    volumes:
      - ~/.docker-conf/mssql/data/:/var/lib/mssql/data
    env_file:
      - env.postgres

  rewriting.api:
    ports:
      - "10000:80"
    networks:
      - shared_rewriting
    env_file:
      - env.api

networks:
  shared_rewriting:
    name: rewriting
    driver: bridge