version: '3.4'

services:
  rewriting.postgres:
    image: postgres:latest

  rewriting.api:
    image: ${DOCKER_REGISTRY-}rewritingapi
    build:
      context: .
      dockerfile: Systems/Rewriting.API/Dockerfile
