version: '3.4'

services:
  rewriting.postgres:
    ports:
      - "5432:5432"
    networks:
      - shared_rewriting
    volumes:
      - ~/.docker-conf/mssql/data/:/var/lib/mssql/data
    env_file:
      - env.postgres
    extra_hosts:
      - host.docker.internal:host-gateway

  rewriting.rabbitmq:
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672" 
    networks:
      - shared_rewriting
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    extra_hosts:
      - host.docker.internal:host-gateway
  
  rewriting.redis:
    ports:
      - "6379:6379"
    networks:
      - shared_rewriting
    volumes:
      - ~/.docker-conf/redis/data/:/data
    extra_hosts:
      - host.docker.internal:host-gateway

  rewriting.api:
    ports:
      - "10000:80"
    networks:
      - shared_rewriting
    env_file:
      - env.api
    extra_hosts:
      - host.docker.internal:host-gateway

  rewriting.identity:
    ports:
      - "10001:80"
    networks:
      - shared_rewriting
    env_file:
      - env.identity
    extra_hosts:
      - host.docker.internal:host-gateway

  rewriting.worker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    env_file:
      - env.worker
    extra_hosts:
      - host.docker.internal:host-gateway

  rewriting.webapp:
    ports:
      - "10010:80"
    networks:
      - shared_rewriting
    env_file:
      - env.webapp
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  shared_rewriting:
    name: rewriting
    driver: bridge

