version: '3.4'

services:
  rewriting.postgres:
    image: postgres:latest

  rewriting.api:
    image: ${DOCKER_REGISTRY-}rewritingapi
    build:
      context: .
      dockerfile: Systems/Rewriting.API/Dockerfile
    depends_on:
      - rewriting.postgres

  rewriting.identity:
    image: ${DOCKER_REGISTRY-}rewritingidentity
    build:
      context: .
      dockerfile: Systems/Rewriting.Identity/Dockerfile
    depends_on:
      - rewriting.postgres
      - rewriting.api